### ISSUE TITLE
VS2013 Support

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [Inxton/Tutorials-Inxton.Package.Vortex.Core#1]
For some reason i need to use VS2013. Does Inxton Package support VS2013 version?

**Comment by Inxton-Dev** [comment]
Hi @kumaraswamygaviyappa, there are no plans to support VS2013. As we are moving to net5  and higher we do not maintain the combability with older version of VS. You may however use NET4.8 versions in VS2013 and instead of extensions you may use CLI 

https://docs.inxton.com/docu/articles/units/Inxton.vortex.compiler.console/README.html#command-line-interface-cli

will generate ```cs``` files into [yoursolutionfolder]\_Vortex\out\  folder.
